<?php

namespace App\Repository;

use App\Entity\Bid;
use Doctrine\ORM\EntityRepository;


/**
 * BidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BidRepository extends EntityRepository
{
    /**
     * @param string $id
     *
     * @return Bid|object|null
     */
    public function findByUserId(int $id)
    {
        $em = $this->getEntityManager();

        return $em->getRepository(Bid::class)->findBy(['userId' => $id]);
    }
}
